version: "3.2"

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - localstack
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4563-4599:4563-4599"
      - "8055:8080"
    environment:
      - SERVICES=s3
      - DEBUG=1

