version: "3.2"

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - WAIT_HOSTS=
      - WAIT_HOSTS_TIMEOUT=60
      - WAIT_SLEEP_INTERVAL=1
      - WAIT_HOST_CONNECT_TIMEOUT=5
