version: "3.2"

services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - localstack
    environment:
      - WAIT_HOSTS=localstack:4566
      - WAIT_HOSTS_TIMEOUT=60
      - WAIT_SLEEP_INTERVAL=1
      - WAIT_HOST_CONNECT_TIMEOUT=5
  localstack:
    image: localstack/localstack:0.12.7
    ports:
      - '4566:4566'
    environment:
      - SERVICES=s3
      - DEBUG=1
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "./fixtures/localstack-init:/docker-entrypoint-initaws.d"
